import logging
import re
from typing import List, Dict, Optional

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound
from yt_dlp import YoutubeDL


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def get_video_ids(channel_url: str, max_videos: int = 5) -> List[str]:
    """Return up to max_videos video ids from a channel or playlist URL.

    This is robust to yt-dlp returning a single video dict or an 'entries' listing.
    """
    ydl_opts = {
        "quiet": True,
        "extract_flat": True,
        "skip_download": True,
    }

    video_ids: List[str] = []

    try:
        with YoutubeDL(ydl_opts) as ydl:
            result = ydl.extract_info(channel_url, download=False)

        if not result:
            return []

        # channel/playlist
        if isinstance(result, dict) and "entries" in result:
            for entry in result["entries"][:max_videos]:
                if not entry:
                    continue
                video_id = entry.get("id")
                if video_id and len(video_id) == 11:
                    video_ids.append(video_id)
        else:
            # single video URL
            if isinstance(result, dict):
                vid = result.get("id")
                if vid and len(vid) == 11:
                    video_ids.append(vid)

    except Exception as e:
        logger.exception("Failed to extract video ids from %s: %s", channel_url, e)

    logger.info("Found video ids: %s", video_ids)
    return video_ids


def clean_text(text: str) -> str:
    """Clean transcript text:
    - remove timestamps, bracketed notes
    - remove URLs
    - remove sponsor/subscribe boilerplate lines
    - collapse repeated words and normalize whitespace
    """
    if not text:
        return ""

    # remove timestamps like [00:01:23] or 00:01:23
    text = re.sub(r"\[?\(?\d{1,2}:\d{2}(?::\d{2})?\)?\]?", " ", text)

    # remove bracketed non-speech markers
    text = re.sub(r"\(music\)|\[music\]|\(applause\)|\(laughs\)", " ", text, flags=re.IGNORECASE)

    # remove URLs and emails
    text = re.sub(r"https?://\S+|www\.\S+|\S+@\S+", " ", text)

    # drop sentences that look like sponsor or subscribe calls (heuristic)
    sponsor_patterns = [
        r"\bsubscribe\b",
        r"like this video",
        r"visit our sponsor",
        r"\bsponsor\b",
        r"\bsponsored\b",
        r"check out the link",
        r"buy now",
        r"follow (us|me)",
        r"click the link",
    ]

    # split into sentences and filter out only the offending sentences
    sentences = re.split(r'(?<=[.!?])\s+', text)
    kept = []
    for s in sentences:
        low = s.lower()
        if any(re.search(pat, low) for pat in sponsor_patterns):
            continue
        kept.append(s)
    text = " ".join(kept)

    # collapse repeated short word sequences like 'subscribe subscribe subscribe' -> 'subscribe'
    text = re.sub(r"\b(\w+)(?:\s+\1){2,}\b", r"\1", text, flags=re.IGNORECASE)

    # collapse repeated punctuation
    text = re.sub(r"([!?.]){2,}", r"\1", text)

    # normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


def get_transcript(video_id: str) -> Optional[Dict[str, str]]:
    """Fetch the best available English transcript for a video.

    Preference order:
      1) manually created English transcript
      2) auto-generated English transcript

    Returns None if no transcript is available.
    """
    try:
        # Prefer the newer API which exposes transcript metadata if available
        if hasattr(YouTubeTranscriptApi, "list_transcripts"):
            transcripts = YouTubeTranscriptApi.list_transcripts(video_id)

            transcript = None
            # prefer manually created English
            try:
                transcript = transcripts.find_manually_created_transcript(["en"])
            except NoTranscriptFound:
                transcript = None

            # fallback to any English transcript (may be autogenerated)
            if transcript is None:
                try:
                    transcript = transcripts.find_transcript(["en"])  # may return manual or generated
                except NoTranscriptFound:
                    transcript = None

            # last ditch: try generated explicitly
            if transcript is None:
                try:
                    transcript = transcripts.find_generated_transcript(["en"])
                except NoTranscriptFound:
                    transcript = None

            if transcript is None:
                logger.info("No English transcript for video %s", video_id)
                return None

            segments = transcript.fetch()
            text = " ".join([seg.get("text", "") for seg in segments])

        else:
            # Older youtube_transcript_api: fall back to fetch (or get_transcript if present)
            try:
                # many installs expose `fetch` as an instance method
                inst = None
                try:
                    inst = YouTubeTranscriptApi()
                except Exception:
                    inst = None

                if inst is not None and hasattr(inst, "fetch"):
                    segments = inst.fetch(video_id)
                    pieces = []
                    for seg in segments:
                        if isinstance(seg, dict):
                            pieces.append(seg.get("text", ""))
                        else:
                            pieces.append(getattr(seg, "text", ""))
                    text = " ".join(pieces)
                elif hasattr(YouTubeTranscriptApi, "get_transcript"):
                    segments = YouTubeTranscriptApi.get_transcript(video_id)
                    pieces = []
                    for seg in segments:
                        if isinstance(seg, dict):
                            pieces.append(seg.get("text", ""))
                        else:
                            pieces.append(getattr(seg, "text", ""))
                    text = " ".join(pieces)
                else:
                    logger.info("youtube_transcript_api available but no compatible fetch/get_transcript method for %s", video_id)
                    return None
            except Exception as e:
                logger.info("No transcript available (fallback) for %s: %s", video_id, e)
                return None

        cleaned = clean_text(text)

        logger.info("Fetched transcript for %s (chars=%d)", video_id, len(cleaned))
        return {"video_id": video_id, "text": cleaned}

    except TranscriptsDisabled:
        logger.info("Transcripts disabled for video %s", video_id)
        return None
    except NoTranscriptFound:
        logger.info("No transcript found for video %s", video_id)
        return None
    except Exception as e:
        logger.exception("Error fetching transcript for %s: %s", video_id, e)
        return None


def fetch_channel_transcripts(channel_url: str, max_videos: int = 5) -> List[Dict[str, str]]:
    video_ids = get_video_ids(channel_url, max_videos=max_videos)

    logger.info("VIDEO IDS: %s", video_ids)

    transcripts: List[Dict[str, str]] = []

    for vid in video_ids:
        rec = get_transcript(vid)
        if rec and rec.get("text"):
            transcripts.append({"video_id": vid, "text": rec["text"]})

    logger.info("TRANSCRIPTS COUNT: %d", len(transcripts))
    return transcripts